[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features=["serde"]}
argonautica = "0.2"
diesel = { version = "2.2.0", features = ["postgres", "chrono"] }
uuid = {version = "1.17.0", features = ["v4"]}
dotenv = "0.15.0"
